#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if [[ ! -f .env ]]; then
  cp .env.example .env
fi

set -a
source .env
set +a

echo "== Semantic cache validation wrapper =="
echo "This validates Oracle primary plus True Cache readiness, then runs deterministic semantic-cache scenarios."
echo "The Java app prints scenario-level decision, route, provider calls, distance, and threshold details."
echo "Generated reports are written under reports/generated/."
echo

echo "Checking primary database and registered True Cache application login readiness..."
./scripts/wait-for-oracle.sh
echo "Building the Spring Boot validation app..."
./mvnw -q -pl app -am package -DskipTests
echo "Running deterministic semantic-cache scenarios..."
env -u DEBUG java -jar app/target/semantic-cache-oracle-app-0.1.0-SNAPSHOT.jar

primary_system_sql() {
  docker exec -i semantic-cache-oracle-db bash -lc "sqlplus -s system/'${ORACLE_PWD}'@//localhost:1521/FREE" <<SQL
set pagesize 100 linesize 200 feedback off verify off
$1
exit
SQL
}

primary_app_sql() {
  docker exec -i semantic-cache-oracle-db bash -lc "sqlplus -s ${APP_USER}/'${APP_PASSWORD}'@//localhost:1521/FREEPDB1" <<SQL
set pagesize 100 linesize 200 feedback off verify off
$1
exit
SQL
}

true_cache_system_sql() {
  docker exec -i semantic-cache-true-cache bash -lc "sqlplus -s system/'${ORACLE_PWD}'@//localhost:1521/FREEPDB1" <<SQL
set pagesize 100 linesize 200 feedback off verify off
$1
exit
SQL
}

true_cache_app_sql() {
  docker exec -i semantic-cache-true-cache bash -lc "sqlplus -s ${APP_USER}/'${APP_PASSWORD}'@//localhost:1521/semcache_pdb_tc" <<SQL
set pagesize 100 linesize 200 feedback off verify off
$1
exit
SQL
}

echo "Writing database-boundary evidence for the primary and True Cache services..."
evidence_file="reports/generated/validation-evidence.md"
{
  echo "# Validation Evidence"
  echo
  echo "Generated by \`./scripts/run-validation.sh\`."
  echo
  echo "## Environment"
  echo
  echo "- Primary service: \`semantic-cache-oracle-db\`"
  echo "- True Cache service: \`semantic-cache-true-cache\`"
  echo "- Primary PDB service: \`FREEPDB1\`"
  echo "- Registered True Cache PDB service: \`semcache_pdb_tc\`"
  echo
  echo "## Primary Database Evidence"
  echo
  echo "Primary database logging mode:"
  echo
  echo '```text'
  primary_system_sql 'select log_mode, force_logging from v$database;'
  echo '```'
  echo
  echo "Primary schema objects:"
  echo
  echo '```text'
  primary_app_sql "select table_name from user_tables where table_name in ('SEM_CACHE_ENTRY', 'SEM_CACHE_EVENT') order by table_name;"
  echo '```'
  echo
  echo "## True Cache Evidence"
  echo
  echo "True Cache database mode:"
  echo
  echo '```text'
  true_cache_system_sql 'select open_mode, database_role from v$database;'
  echo '```'
  echo
  echo "Application schema through the registered True Cache service:"
  echo
  echo '```text'
  true_cache_app_sql "select table_name from user_tables where table_name in ('SEM_CACHE_ENTRY', 'SEM_CACHE_EVENT') order by table_name;"
  echo '```'
  echo
  echo "Vector expression through the registered True Cache service:"
  echo
  echo '```text'
  true_cache_app_sql "select vector_distance(to_vector('[0.1,0.2,0.3,0.4]'), to_vector('[0.1,0.2,0.3,0.4]'), cosine) as distance from dual;"
  echo '```'
  echo
  echo "Event count through the registered True Cache service:"
  echo
  echo '```text'
  true_cache_app_sql "select count(*) as event_count from sem_cache_event;"
  echo '```'
} > "$evidence_file"

echo
echo "Validation summary reports:"
echo "- reports/generated/validation-events.csv - per-scenario decisions, routes, distances, thresholds, provider calls, and latency fields"
echo "- reports/generated/validation-summary.json - machine-readable validation summary"
echo "- reports/generated/validation-summary.md - reader-readable scenario summary"
echo "- reports/generated/validation-evidence.md - primary and True Cache database-boundary evidence"
ls -1 reports/generated/validation-events.csv reports/generated/validation-summary.json reports/generated/validation-summary.md "$evidence_file"
